### ISSUE TITLE
Add AADA token for listing

### ISSUE THREAD

**Issue by DSG87** [MuesliSwapTeam/muesliswap-cardano-listing#97]
Hey Guys!

Can we please add AADA Finance token to MuesliSwap?

With the success of Liqwid Finance being added to MuesliSwap, AADA would be a great addition as well.

There are currently 1.375 million tokens from the non-lock up private sale in circulation, but with no where to list/trade (out of a total of 35.75 million AADA tokens). MuesliSwap would become the go-to place to buy/sell/trade AADA before it lists anywhere else!

I've created a JSON file for the token. How can I upload it?

Cheers!!!

**Comment by MuesliSwapTeam** [comment]
Hi, we have listed it yesterday - thank you for reaching out :)
